export const APIKEY = "b6f0e3f0160b40a49b66f75d55608570"; // https://spoonacular.com/food-api

export const dummyText =
  "Lorem ipsum dolor sit amet, consectetuer adipiscing eli Aliquam tincidunt mauris eu risus Vestibulum auctor dapibus neque. Nunc dignissim risus id metus. Cras ornare tristique elit. Vivamus vestibulum ntulla nec ante. Praesent placerat risus quis eros. Fusce pellentesque suscipit nibh. Integer vitae libero ac risus egestas placerat Vestibulum commodo felis quis tortor. Ut aliquam sollicitudin leo. Cras iaculis ultricies nulla. Donec quis dui at dolor tempor interdum.";
``;
export const dummySteps = [
  {
    equipment: [],
    ingredients: [],
    number: 1,
    step: "Top 4 slices of bread with a layer of mozzarella, tomato, avocado slices and another layer of mozzarella.",
  },
  {
    equipment: [],
    ingredients: [],
    number: 2,
    step: "Spread a little butter on both outsides of the sandwiches and grill until bread is toasted and cheese is melted.",
  },
  { equipment: [], ingredients: [], number: 3, step: "Serve warm and enjoy!" },
];

export const fridgeDummyItems = [
  {
    aisle: "Frozen",
    category: "grain",
    image: "frozen-waffles.png",
    itemID: 28015,
    name: "frozen waffles",
    quantity: 2,
    userID: "NNc788WL4JbPJKSkfA1G1bftV6I3",
  },
  {
    aisle: "Milk, Eggs, Other Dairy",
    category: "protein",
    image: "egg.png",
    itemID: 1123,
    name: "egg",
    quantity: 2,
    userID: "NNc788WL4JbPJKSkfA1G1bftV6I3",
  },
  {
    aisle: "Produce",
    category: "fruit",
    image: "bananas.jpg",
    itemID: 9040,
    name: "banana",
    quantity: 3,
    userID: "NNc788WL4JbPJKSkfA1G1bftV6I3",
  },
  {
    aisle: "Milk, Eggs, Other Dairy",
    category: "dairy",
    image: "milk.png",
    itemID: 1011077,
    name: "whole milk",
    quantity: 2,
    userID: "NNc788WL4JbPJKSkfA1G1bftV6I3",
  },
  {
    aisle: "Meat",
    category: "protein",
    image: "fresh-ground-beef.jpg",
    itemID: 10023572,
    name: "ground chuck",
    quantity: 3,
    userID: "NNc788WL4JbPJKSkfA1G1bftV6I3",
  },
];
export const dummyBulk = [
  {
    aggregateLikes: 3,
    analyzedInstructions: {
      name: "",
      steps: [
        {
          equipment: [Array],
          ingredients: [Array],
          number: 1,
          step: "Combine the sour cream, mayonnaise (or yogurt), Worcestershire sauce, garlic, and vinegar in a large bowl.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 2,
          step: "Whisk together.  Then fold in the cheese and parsley.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 3,
          step: "Cut the lettuce into four wedges.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 4,
          step: "Pour the dressing on top.",
        },
      ],
    },
    approved: 2,
    cheap: false,
    cookingMinutes: -1,
    creditsText: "foodista.com",
    cuisines: [],
    dairyFree: false,
    diets: ["lacto ovo vegetarian"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    extendedIngredients: [
      {
        aisle: "Milk, Eggs, Other Dairy",
        amount: 1.0,
        consitency: "solid",
        id: 1001,
        image: "butter-sliced.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 2.0,
        consitency: "solid",
        id: 10011135,
        image: "cauliflower.jpg",
        measures: {
          metric: {
            amount: 473.176,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 2.0,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        name: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        unit: "cups",
      },
      {
        aisle: "Cheese",
        amount: 2.0,
        consitency: "solid",
        id: 1041009,
        image: "cheddar-cheese.png",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["grated", "(I used romano)"],
        name: "cheese",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        unit: "tbsp",
      },
      {
        aisle: "Oil, Vinegar, Salad Dressing",
        amount: 1.0,
        consitency: "liquid",
        id: 1034053,
        image: "olive-oil.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 5.0,
        consitency: "solid",
        id: 11215,
        image: "garlic.jpg",
        measures: {
          metric: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
          us: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
        },
        meta: [],
        name: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        unit: "cloves",
      },
      {
        aisle: "Pasta and Rice",
        amount: 6.0,
        consitency: "solid",
        id: 20420,
        image: "fusilli.jpg",
        measures: {
          metric: {
            amount: 170.097,
            unitLong: "grams",
            unitShort: "g",
          },
          us: {
            amount: 6.0,
            unitLong: "ounces",
            unitShort: "oz",
          },
        },
        meta: ["(I used linguine)"],
        name: "pasta",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        unit: "ounces",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1032009,
        image: "red-pepper-flakes.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
          us: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
        },
        meta: ["red"],
        name: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        unit: "pinches",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1102047,
        image: "salt-and-pepper.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
          us: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
        },
        meta: ["to taste"],
        name: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        unit: "servings",
      },
      {
        aisle: "Produce",
        amount: 3.0,
        consitency: "solid",
        id: 11291,
        image: "spring-onions.jpg",
        measures: {
          metric: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
          us: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
        },
        meta: ["white", "green", "separated", "chopped"],
        name: "scallions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        unit: "",
      },
      {
        aisle: "Alcoholic Beverages",
        amount: 2.0,
        consitency: "liquid",
        id: 14106,
        image: "white-wine.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["white"],
        name: "white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        unit: "tbsp",
      },
      {
        aisle: "Pasta and Rice",
        amount: 0.25,
        consitency: "solid",
        id: 99025,
        image: "breadcrumbs.jpg",
        measures: {
          metric: {
            amount: 59.147,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 0.25,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["whole wheat", "(I used panko)"],
        name: "whole wheat bread crumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        unit: "cup",
      },
    ],
    gaps: "no",
    glutenFree: false,
    healthScore: 16,
    id: 633167,
    image: "https://spoonacular.com/recipeImages/633167-556x370.jpg",
    imageType: "jpg",
    instructions:
      "Top 4 slices of bread with a layer of mozzarella, tomato, avocado slices and another layer of mozzarella.Spread a little butter on both outsides of the sandwiches and grill until bread is toasted and cheese is melted.Serve warm and enjoy!",
    lowFodmap: false,
    nutrition: {
      caloricBreakdown: [Object],
      flavonoids: [Array],
      ingredients: [Array],
      nutrients: [Array],
      properties: [Array],
      weightPerServing: [Object],
    },
    occasions: [],
    openLicense: 2,
    originalId: null,
    preparationMinutes: -1,
    pricePerServing: 173,
    readyInMinutes: 45,
    report: null,
    servings: 4,
    sourceName: "foodista.com",
    sourceUrl:
      "https://www.foodista.com/recipe/5D3FD6GZ/avocado-tomato-mozzarella-paninisandwiches",
    spoonacularScore: 10.584503173828125,
    spoonacularSourceUrl:
      "https://spoonacular.com/avocado-tomato-mozzarella-panini-sandwiches-633167",
    summary:
      'Avocado Tomato & Mozzarella Panini/sandwiches is a main course that serves 4. One portion of this dish contains about <b>18g of protein</b>, <b>18g of fat</b>, and a total of <b>506 calories</b>. For <b>$1.73 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. 3 people were glad they tried this recipe. It is a good option if you\'re following a <b>lacto ovo vegetarian</b> diet. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. A mixture of avocado, bread, tomatoe, and a handful of other ingredients are all it takes to make this recipe so tasty. Overall, this recipe earns a <b>solid spoonacular score of 61%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/avocado-tomato-mozzarella-panini-633165">Avocado Tomato & Mozzarella Panini</a>, <a href="https://spoonacular.com/recipes/mozzarella-turkey-panini-sandwiches-275394">Mozzarella-Turkey Panini Sandwiches</a>, and <a href="https://spoonacular.com/recipes/tomato-mozzarella-and-basil-panini-782639">Tomato, Mozzarella, and Basil Panini</a>.',
    suspiciousDataScore: 100,
    sustainable: false,
    tips: { cooking: [Array], green: [Array], health: [Array], price: [Array] },
    title: "Avocado Tomato & Mozzarella Panini/sandwiches",
    unknownIngredients: [[Object], [Object]],
    userTags: [],
    vegan: false,
    vegetarian: true,
    veryHealthy: false,
    veryPopular: false,
    weightWatcherSmartPoints: 16,
    winePairing: {
      pairedWines: [Array],
      pairingText: "",
      productMatches: [Array],
    },
  },
  {
    aggregateLikes: 1,
    analyzedInstructions: {
      name: "",
      steps: [
        {
          equipment: [Array],
          ingredients: [Array],
          number: 1,
          step: "Combine the sour cream, mayonnaise (or yogurt), Worcestershire sauce, garlic, and vinegar in a large bowl.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 2,
          step: "Whisk together.  Then fold in the cheese and parsley.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 3,
          step: "Cut the lettuce into four wedges.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 4,
          step: "Pour the dressing on top.",
        },
      ],
    },
    approved: 2,
    cheap: false,
    cookingMinutes: -1,
    creditsText: "foodista.com",
    cuisines: [],
    dairyFree: false,
    diets: ["lacto ovo vegetarian"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    extendedIngredients: [
      {
        aisle: "Milk, Eggs, Other Dairy",
        amount: 1.0,
        consitency: "solid",
        id: 1001,
        image: "butter-sliced.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 2.0,
        consitency: "solid",
        id: 10011135,
        image: "cauliflower.jpg",
        measures: {
          metric: {
            amount: 473.176,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 2.0,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        name: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        unit: "cups",
      },
      {
        aisle: "Cheese",
        amount: 2.0,
        consitency: "solid",
        id: 1041009,
        image: "cheddar-cheese.png",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["grated", "(I used romano)"],
        name: "cheese",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        unit: "tbsp",
      },
      {
        aisle: "Oil, Vinegar, Salad Dressing",
        amount: 1.0,
        consitency: "liquid",
        id: 1034053,
        image: "olive-oil.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 5.0,
        consitency: "solid",
        id: 11215,
        image: "garlic.jpg",
        measures: {
          metric: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
          us: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
        },
        meta: [],
        name: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        unit: "cloves",
      },
      {
        aisle: "Pasta and Rice",
        amount: 6.0,
        consitency: "solid",
        id: 20420,
        image: "fusilli.jpg",
        measures: {
          metric: {
            amount: 170.097,
            unitLong: "grams",
            unitShort: "g",
          },
          us: {
            amount: 6.0,
            unitLong: "ounces",
            unitShort: "oz",
          },
        },
        meta: ["(I used linguine)"],
        name: "pasta",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        unit: "ounces",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1032009,
        image: "red-pepper-flakes.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
          us: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
        },
        meta: ["red"],
        name: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        unit: "pinches",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1102047,
        image: "salt-and-pepper.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
          us: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
        },
        meta: ["to taste"],
        name: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        unit: "servings",
      },
      {
        aisle: "Produce",
        amount: 3.0,
        consitency: "solid",
        id: 11291,
        image: "spring-onions.jpg",
        measures: {
          metric: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
          us: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
        },
        meta: ["white", "green", "separated", "chopped"],
        name: "scallions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        unit: "",
      },
      {
        aisle: "Alcoholic Beverages",
        amount: 2.0,
        consitency: "liquid",
        id: 14106,
        image: "white-wine.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["white"],
        name: "white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        unit: "tbsp",
      },
      {
        aisle: "Pasta and Rice",
        amount: 0.25,
        consitency: "solid",
        id: 99025,
        image: "breadcrumbs.jpg",
        measures: {
          metric: {
            amount: 59.147,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 0.25,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["whole wheat", "(I used panko)"],
        name: "whole wheat bread crumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        unit: "cup",
      },
    ],
    gaps: "no",
    glutenFree: false,
    healthScore: 16,
    id: 633165,
    image: "https://spoonacular.com/recipeImages/633165-556x370.jpg",
    imageType: "jpg",
    instructions:
      "Top 4 slices of bread with a layer of mozzarella, tomato, avocado slices and another layer of mozzarella.Spread a little butter on both outsides of the sandwiches and grill until bread is toasted and cheese is melted.Serve warm and enjoy!",
    lowFodmap: false,
    nutrition: {
      caloricBreakdown: [Object],
      flavonoids: [Array],
      ingredients: [Array],
      nutrients: [Array],
      properties: [Array],
      weightPerServing: [Object],
    },
    occasions: [],
    openLicense: 2,
    originalId: null,
    preparationMinutes: -1,
    pricePerServing: 173,
    readyInMinutes: 45,
    report: null,
    servings: 4,
    sourceName: "foodista.com",
    sourceUrl:
      "https://www.foodista.com/recipe/NQ654TSM/avocado-tomato-mozzarella-panini",
    spoonacularScore: 10.584576606750488,
    spoonacularSourceUrl:
      "https://spoonacular.com/avocado-tomato-mozzarella-panini-633165",
    summary:
      'The recipe Avocado Tomato & Mozzarella Panini can be made <b>in around 45 minutes</b>. One serving contains <b>506 calories</b>, <b>18g of protein</b>, and <b>18g of fat</b>. For <b>$1.73 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. It works well as an affordable main course. This recipe is liked by 1 foodies and cooks. It is brought to you by Foodista. A mixture of butter, tomatoe, mozzarella, and a handful of other ingredients are all it takes to make this recipe so yummy. It is a good option if you\'re following a <b>lacto ovo vegetarian</b> diet. Overall, this recipe earns a <b>solid spoonacular score of 57%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/avocado-tomato-mozzarella-panini-sandwiches-633167">Avocado Tomato & Mozzarella Panini/sandwiches</a>, <a href="https://spoonacular.com/recipes/tapenade-mozzarella-and-tomato-panini-497300">Tapenade, Mozzarella, and Tomato Panini</a>, and <a href="https://spoonacular.com/recipes/roasted-tomato-mozzarella-panini-842552">Roasted Tomato Mozzarella Panini</a>.',
    suspiciousDataScore: 100,
    sustainable: false,
    tips: { cooking: [Array], green: [Array], health: [Array], price: [Array] },
    title: "Avocado Tomato & Mozzarella Panini",
    unknownIngredients: [[Object], [Object]],
    userTags: [],
    vegan: false,
    vegetarian: true,
    veryHealthy: false,
    veryPopular: false,
    weightWatcherSmartPoints: 16,
    winePairing: {
      pairedWines: [Array],
      pairingText: "",
      productMatches: [Array],
    },
  },
  {
    aggregateLikes: 7,
    analyzedInstructions: {
      name: "",
      steps: [
        {
          equipment: [Array],
          ingredients: [Array],
          number: 1,
          step: "Combine the sour cream, mayonnaise (or yogurt), Worcestershire sauce, garlic, and vinegar in a large bowl.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 2,
          step: "Whisk together.  Then fold in the cheese and parsley.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 3,
          step: "Cut the lettuce into four wedges.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 4,
          step: "Pour the dressing on top.",
        },
      ],
    },
    approved: 2,
    cheap: false,
    cookingMinutes: 4,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    cuisines: [],
    dairyFree: false,
    diets: ["gluten free", "lacto ovo vegetarian"],
    dishTypes: ["morning meal", "brunch", "breakfast"],
    extendedIngredients: [
      {
        aisle: "Milk, Eggs, Other Dairy",
        amount: 1.0,
        consitency: "solid",
        id: 1001,
        image: "butter-sliced.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 2.0,
        consitency: "solid",
        id: 10011135,
        image: "cauliflower.jpg",
        measures: {
          metric: {
            amount: 473.176,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 2.0,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        name: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        unit: "cups",
      },
      {
        aisle: "Cheese",
        amount: 2.0,
        consitency: "solid",
        id: 1041009,
        image: "cheddar-cheese.png",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["grated", "(I used romano)"],
        name: "cheese",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        unit: "tbsp",
      },
      {
        aisle: "Oil, Vinegar, Salad Dressing",
        amount: 1.0,
        consitency: "liquid",
        id: 1034053,
        image: "olive-oil.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 5.0,
        consitency: "solid",
        id: 11215,
        image: "garlic.jpg",
        measures: {
          metric: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
          us: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
        },
        meta: [],
        name: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        unit: "cloves",
      },
      {
        aisle: "Pasta and Rice",
        amount: 6.0,
        consitency: "solid",
        id: 20420,
        image: "fusilli.jpg",
        measures: {
          metric: {
            amount: 170.097,
            unitLong: "grams",
            unitShort: "g",
          },
          us: {
            amount: 6.0,
            unitLong: "ounces",
            unitShort: "oz",
          },
        },
        meta: ["(I used linguine)"],
        name: "pasta",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        unit: "ounces",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1032009,
        image: "red-pepper-flakes.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
          us: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
        },
        meta: ["red"],
        name: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        unit: "pinches",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1102047,
        image: "salt-and-pepper.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
          us: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
        },
        meta: ["to taste"],
        name: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        unit: "servings",
      },
      {
        aisle: "Produce",
        amount: 3.0,
        consitency: "solid",
        id: 11291,
        image: "spring-onions.jpg",
        measures: {
          metric: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
          us: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
        },
        meta: ["white", "green", "separated", "chopped"],
        name: "scallions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        unit: "",
      },
      {
        aisle: "Alcoholic Beverages",
        amount: 2.0,
        consitency: "liquid",
        id: 14106,
        image: "white-wine.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["white"],
        name: "white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        unit: "tbsp",
      },
      {
        aisle: "Pasta and Rice",
        amount: 0.25,
        consitency: "solid",
        id: 99025,
        image: "breadcrumbs.jpg",
        measures: {
          metric: {
            amount: 59.147,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 0.25,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["whole wheat", "(I used panko)"],
        name: "whole wheat bread crumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        unit: "cup",
      },
    ],
    gaps: "no",
    glutenFree: true,
    healthScore: 30,
    id: 638604,
    image: "https://spoonacular.com/recipeImages/638604-556x370.jpg",
    imageType: "jpg",
    instructions:
      "<p>-In a small bowl, add oatmeal, yogurt, milk and combine. Let it sit for few minutes or several hours in the refrigerator.  Then add apples, banana, dried fruits and stir until well combined. Top with nuts before serving.</p><p>Note: it tastes best when allowed to sit overnight. Add fruits right before serving to prevent browning and being mushy.</p>",
    license: "CC BY 3.0",
    lowFodmap: false,
    nutrition: {
      caloricBreakdown: [Object],
      flavonoids: [Array],
      ingredients: [Array],
      nutrients: [Array],
      properties: [Array],
      weightPerServing: [Object],
    },
    occasions: [],
    openLicense: 2,
    originalId: null,
    preparationMinutes: 6,
    pricePerServing: 188.99,
    readyInMinutes: 10,
    report: null,
    servings: 1,
    sourceName: "Foodista",
    sourceUrl: "https://www.foodista.com/recipe/K232GXCT/chilled-swiss-oatmeal",
    spoonacularScore: 87.9686050415039,
    spoonacularSourceUrl:
      "https://spoonacular.com/chilled-swiss-oatmeal-638604",
    summary:
      'Chilled Swiss Oatmeal takes roughly <b>10 minutes</b> from beginning to end. This recipe serves 1 and costs $1.89 per serving. One portion of this dish contains around <b>17g of protein</b>, <b>14g of fat</b>, and a total of <b>523 calories</b>. It is brought to you by Foodista. Not a lot of people made this recipe, and 7 would say it hit the spot. It works well as a breakfast. A mixture of apple, cranberry, banana, and a handful of other ingredients are all it takes to make this recipe so scrumptious. It is a good option if you\'re following a <b>gluten free and lacto ovo vegetarian</b> diet. Overall, this recipe earns an <b>outstanding spoonacular score of 87%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/chilled-swiss-oatmeal-1629215">Chilled Swiss Oatmeal</a>, <a href="https://spoonacular.com/recipes/chilled-swiss-oatmeal-1371821">Chilled Swiss Oatmeal</a>, and <a href="https://spoonacular.com/recipes/quick-healthy-breakfast-chilled-swiss-oatmeal-1229091">Quick & Healthy Breakfast – Chilled Swiss Oatmeal</a>.',
    suspiciousDataScore: 98.20503,
    sustainable: false,
    tips: { cooking: [Array], green: [Array], health: [Array], price: [Array] },
    title: "Chilled Swiss Oatmeal",
    unknownIngredients: [],
    userTags: [],
    vegan: false,
    vegetarian: true,
    veryHealthy: false,
    veryPopular: false,
    weightWatcherSmartPoints: 13,
    winePairing: {
      pairedWines: [Array],
      pairingText: "",
      productMatches: [Array],
    },
  },
  {
    aggregateLikes: 1,
    analyzedInstructions: {
      name: "",
      steps: [
        {
          equipment: [Array],
          ingredients: [Array],
          number: 1,
          step: "Combine the sour cream, mayonnaise (or yogurt), Worcestershire sauce, garlic, and vinegar in a large bowl.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 2,
          step: "Whisk together.  Then fold in the cheese and parsley.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 3,
          step: "Cut the lettuce into four wedges.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 4,
          step: "Pour the dressing on top.",
        },
      ],
    },
    approved: 2,
    cheap: false,
    cookingMinutes: -1,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    cuisines: [],
    dairyFree: false,
    diets: ["gluten free", "lacto ovo vegetarian", "primal"],
    dishTypes: [
      "side dish",
      "antipasti",
      "salad",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    extendedIngredients: [
      {
        aisle: "Milk, Eggs, Other Dairy",
        amount: 1.0,
        consitency: "solid",
        id: 1001,
        image: "butter-sliced.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 2.0,
        consitency: "solid",
        id: 10011135,
        image: "cauliflower.jpg",
        measures: {
          metric: {
            amount: 473.176,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 2.0,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        name: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        unit: "cups",
      },
      {
        aisle: "Cheese",
        amount: 2.0,
        consitency: "solid",
        id: 1041009,
        image: "cheddar-cheese.png",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["grated", "(I used romano)"],
        name: "cheese",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        unit: "tbsp",
      },
      {
        aisle: "Oil, Vinegar, Salad Dressing",
        amount: 1.0,
        consitency: "liquid",
        id: 1034053,
        image: "olive-oil.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 5.0,
        consitency: "solid",
        id: 11215,
        image: "garlic.jpg",
        measures: {
          metric: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
          us: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
        },
        meta: [],
        name: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        unit: "cloves",
      },
      {
        aisle: "Pasta and Rice",
        amount: 6.0,
        consitency: "solid",
        id: 20420,
        image: "fusilli.jpg",
        measures: {
          metric: {
            amount: 170.097,
            unitLong: "grams",
            unitShort: "g",
          },
          us: {
            amount: 6.0,
            unitLong: "ounces",
            unitShort: "oz",
          },
        },
        meta: ["(I used linguine)"],
        name: "pasta",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        unit: "ounces",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1032009,
        image: "red-pepper-flakes.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
          us: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
        },
        meta: ["red"],
        name: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        unit: "pinches",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1102047,
        image: "salt-and-pepper.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
          us: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
        },
        meta: ["to taste"],
        name: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        unit: "servings",
      },
      {
        aisle: "Produce",
        amount: 3.0,
        consitency: "solid",
        id: 11291,
        image: "spring-onions.jpg",
        measures: {
          metric: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
          us: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
        },
        meta: ["white", "green", "separated", "chopped"],
        name: "scallions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        unit: "",
      },
      {
        aisle: "Alcoholic Beverages",
        amount: 2.0,
        consitency: "liquid",
        id: 14106,
        image: "white-wine.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["white"],
        name: "white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        unit: "tbsp",
      },
      {
        aisle: "Pasta and Rice",
        amount: 0.25,
        consitency: "solid",
        id: 99025,
        image: "breadcrumbs.jpg",
        measures: {
          metric: {
            amount: 59.147,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 0.25,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["whole wheat", "(I used panko)"],
        name: "whole wheat bread crumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        unit: "cup",
      },
    ],
    gaps: "no",
    glutenFree: true,
    healthScore: 5,
    id: 664912,
    image: "https://spoonacular.com/recipeImages/664912-556x370.jpg",
    imageType: "jpg",
    instructions:
      "Core and dice applesDice celeryMix apples, celery and lemon juice with ChavrieServe on a bed of lettuce and top with walnut pieces",
    license: "CC BY 3.0",
    lowFodmap: false,
    nutrition: {
      caloricBreakdown: [Object],
      flavonoids: [Array],
      ingredients: [Array],
      nutrients: [Array],
      properties: [Array],
      weightPerServing: [Object],
    },
    occasions: [],
    openLicense: 2,
    originalId: null,
    preparationMinutes: -1,
    pricePerServing: 51.25,
    readyInMinutes: 45,
    report: null,
    servings: 6,
    sourceName: "Foodista",
    sourceUrl:
      "https://www.foodista.com/recipe/8QCV3GHR/waldorf-salad-with-fresh-goat-cheese",
    spoonacularScore: 11.950213432312012,
    spoonacularSourceUrl:
      "https://spoonacular.com/waldorf-salad-with-fresh-goat-cheese-664912",
    summary:
      'Waldorf Salad With Fresh Goat Cheese might be a good recipe to expand your hor d\'oeuvre recipe box. Watching your figure? This gluten free, lacto ovo vegetarian, and primal recipe has <b>96 calories</b>, <b>2g of protein</b>, and <b>6g of fat</b> per serving. This recipe serves 6. For <b>51 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. A mixture of ea. tasty apples, ea. stalk of celery, lemon juice, and a handful of other ingredients are all it takes to make this recipe so tasty. 1 person found this recipe to be delicious and satisfying. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. It is brought to you by Foodista. With a spoonacular <b>score of 37%</b>, this dish is not so outstanding. Similar recipes include <a href="https://spoonacular.com/recipes/chicken-kale-waldorf-salad-with-avocado-goat-cheese-838496">Chicken Kale Waldorf Salad with Avocado & Goat Cheese</a>, <a href="https://spoonacular.com/recipes/fresh-peach-with-goat-cheese-side-salad-643561">Fresh Peach With Goat Cheese Side Salad</a>, and <a href="https://spoonacular.com/recipes/fresh-corn-tomato-salad-with-goat-cheese-766709">Fresh Corn & Tomato Salad with Goat Cheese</a>.',
    suspiciousDataScore: 6.0949974,
    sustainable: false,
    tips: { cooking: [Array], green: [Array], health: [Array], price: [Array] },
    title: "Waldorf Salad With Fresh Goat Cheese",
    unknownIngredients: [],
    userTags: [],
    vegan: false,
    vegetarian: true,
    veryHealthy: false,
    veryPopular: false,
    weightWatcherSmartPoints: 2,
    winePairing: {
      pairedWines: [Array],
      pairingText:
        "Chardonnay, Alcoholic Drink, and White Wine are great choices for Waldorf Salad. Sauvignon Blanc and Gruner Veltliner both have herby notes that complement salads with enough acid to match tart vinaigrettes, while a Chardonnay can be a good pick for creamy salad dressings. The Game of Thrones Chardonnay with a 4.7 out of 5 star rating seems like a good match. It costs about 20 dollars per bottle.",
      productMatches: [Array],
    },
  },
  {
    aggregateLikes: 1,
    analyzedInstructions: {
      name: "",
      steps: [
        {
          equipment: [Array],
          ingredients: [Array],
          number: 1,
          step: "Combine the sour cream, mayonnaise (or yogurt), Worcestershire sauce, garlic, and vinegar in a large bowl.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 2,
          step: "Whisk together.  Then fold in the cheese and parsley.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 3,
          step: "Cut the lettuce into four wedges.",
        },
        {
          equipment: [Array],
          ingredients: [Array],
          number: 4,
          step: "Pour the dressing on top.",
        },
      ],
    },
    approved: 2,
    cheap: false,
    cookingMinutes: -1,
    creditsText: "foodista.com",
    cuisines: ["Mediterranean", "Italian", "European"],
    dairyFree: false,
    diets: ["pescatarian"],
    dishTypes: [
      "antipasti",
      "lunch",
      "main course",
      "starter",
      "snack",
      "appetizer",
      "main dish",
      "antipasto",
      "hor d'oeuvre",
      "dinner",
    ],
    extendedIngredients: [
      {
        aisle: "Milk, Eggs, Other Dairy",
        amount: 1.0,
        consitency: "solid",
        id: 1001,
        image: "butter-sliced.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 2.0,
        consitency: "solid",
        id: 10011135,
        image: "cauliflower.jpg",
        measures: {
          metric: {
            amount: 473.176,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 2.0,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        name: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        unit: "cups",
      },
      {
        aisle: "Cheese",
        amount: 2.0,
        consitency: "solid",
        id: 1041009,
        image: "cheddar-cheese.png",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["grated", "(I used romano)"],
        name: "cheese",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        unit: "tbsp",
      },
      {
        aisle: "Oil, Vinegar, Salad Dressing",
        amount: 1.0,
        consitency: "liquid",
        id: 1034053,
        image: "olive-oil.jpg",
        measures: {
          metric: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
          us: {
            amount: 1.0,
            unitLong: "Tbsp",
            unitShort: "Tbsp",
          },
        },
        meta: [],
        name: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        unit: "tbsp",
      },
      {
        aisle: "Produce",
        amount: 5.0,
        consitency: "solid",
        id: 11215,
        image: "garlic.jpg",
        measures: {
          metric: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
          us: {
            amount: 5.0,
            unitLong: "cloves",
            unitShort: "cloves",
          },
        },
        meta: [],
        name: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        unit: "cloves",
      },
      {
        aisle: "Pasta and Rice",
        amount: 6.0,
        consitency: "solid",
        id: 20420,
        image: "fusilli.jpg",
        measures: {
          metric: {
            amount: 170.097,
            unitLong: "grams",
            unitShort: "g",
          },
          us: {
            amount: 6.0,
            unitLong: "ounces",
            unitShort: "oz",
          },
        },
        meta: ["(I used linguine)"],
        name: "pasta",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        unit: "ounces",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1032009,
        image: "red-pepper-flakes.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
          us: {
            amount: 2.0,
            unitLong: "pinches",
            unitShort: "pinches",
          },
        },
        meta: ["red"],
        name: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        unit: "pinches",
      },
      {
        aisle: "Spices and Seasonings",
        amount: 2.0,
        consitency: "solid",
        id: 1102047,
        image: "salt-and-pepper.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
          us: {
            amount: 2.0,
            unitLong: "servings",
            unitShort: "servings",
          },
        },
        meta: ["to taste"],
        name: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        unit: "servings",
      },
      {
        aisle: "Produce",
        amount: 3.0,
        consitency: "solid",
        id: 11291,
        image: "spring-onions.jpg",
        measures: {
          metric: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
          us: {
            amount: 3.0,
            unitLong: "",
            unitShort: "",
          },
        },
        meta: ["white", "green", "separated", "chopped"],
        name: "scallions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        unit: "",
      },
      {
        aisle: "Alcoholic Beverages",
        amount: 2.0,
        consitency: "liquid",
        id: 14106,
        image: "white-wine.jpg",
        measures: {
          metric: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
          us: {
            amount: 2.0,
            unitLong: "Tbsps",
            unitShort: "Tbsps",
          },
        },
        meta: ["white"],
        name: "white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        unit: "tbsp",
      },
      {
        aisle: "Pasta and Rice",
        amount: 0.25,
        consitency: "solid",
        id: 99025,
        image: "breadcrumbs.jpg",
        measures: {
          metric: {
            amount: 59.147,
            unitLong: "milliliters",
            unitShort: "ml",
          },
          us: {
            amount: 0.25,
            unitLong: "cups",
            unitShort: "cups",
          },
        },
        meta: ["whole wheat", "(I used panko)"],
        name: "whole wheat bread crumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        unit: "cup",
      },
    ],
    gaps: "no",
    glutenFree: false,
    healthScore: 17,
    id: 650651,
    image: "https://spoonacular.com/recipeImages/650651-556x370.jpg",
    imageType: "jpg",
    instructions:
      "Preheat broiler.Mix shrimp with spaghetti sauce and microwave for 1 1/2 - 2 minutes until heated through.Sprinkle parmesan cheese on hoagie rolls and toast under the broiler until cheese melts.Top each roll with half the shrimp mixture and spinach leaves.",
    lowFodmap: false,
    nutrition: {
      caloricBreakdown: [Object],
      flavonoids: [Array],
      ingredients: [Array],
      nutrients: [Array],
      properties: [Array],
      weightPerServing: [Object],
    },
    occasions: [],
    openLicense: 2,
    originalId: null,
    preparationMinutes: -1,
    pricePerServing: 380.13,
    readyInMinutes: 45,
    report: null,
    servings: 2,
    sourceName: "foodista.com",
    sourceUrl:
      "https://www.foodista.com/recipe/476BQSYP/make-it-quick-italian-shrimp-rolls",
    spoonacularScore: 61.773319244384766,
    spoonacularSourceUrl:
      "https://spoonacular.com/make-it-quick-italian-shrimp-rolls-650651",
    summary:
      'The recipe Make It Quick Italian Shrimp Rolls can be made <b>in around 45 minutes</b>. For <b>$3.8 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains roughly <b>37g of protein</b>, <b>8g of fat</b>, and a total of <b>381 calories</b>. This recipe serves 2. 1 person were impressed by this recipe. It is a good option if you\'re following a <b>pescatarian</b> diet. It is brought to you by Foodista. It works well as a hor d\'oeuvre. A mixture of low sugar spaghetti sauce, shrimp, parmesan cheese, and a handful of other ingredients are all it takes to make this recipe so scrumptious. It is a <b>rather expensive</b> recipe for fans of Mediterranean food. Overall, this recipe earns a <b>good spoonacular score of 67%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/quick-cardamom-rolls-174090">Quick Cardamom Rolls</a>, <a href="https://spoonacular.com/recipes/quick-pizza-rolls-408857">Quick Pizza Rolls</a>, and <a href="https://spoonacular.com/recipes/quick-yeast-rolls-1261429">Quick Yeast Rolls</a>.',
    suspiciousDataScore: 0,
    sustainable: false,
    tips: { cooking: [Array], green: [Array], health: [Array], price: [Array] },
    title: "Make It Quick Italian Shrimp Rolls",
    unknownIngredients: [],
    userTags: [],
    vegan: false,
    vegetarian: false,
    veryHealthy: false,
    veryPopular: false,
    weightWatcherSmartPoints: 9,
    winePairing: {
      pairedWines: [Array],
      pairingText:
        "Shrimp works really well with Sauvignon Blanc, Riesling, and Pinot Grigio. These crisp white wines work well with shrimp prepared in a variety of ways, whether grilled, fried, or in garlic sauce. The Save Me San Francisco Bullet Proof Picasso Sauvignon Blanc Wine with a 5 out of 5 star rating seems like a good match. It costs about 20 dollars per bottle.",
      productMatches: [Array],
    },
  },
];
